{{ if eq .Values.withIngress true }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-{{ .Chart.Name }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress_host }}
  rules:
    - host: {{ .Values.ingress_host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: svc-{{ .Chart.Name }}-{{ .Release.Name }}
              servicePort: 3001
  {{ end }}