apiVersion: v1
kind: Service
metadata:
  name: svc-hello-world-web
  namespace: multi-cloud-tech-preview
  labels:
    app: hello-world-frontend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
  selector:
    app: hello-world-frontend
